# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-24 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('u_pass', models.CharField(max_length=40, verbose_name='密码')),
                ('u_email', models.EmailField(max_length=20, verbose_name='邮箱')),
                ('u_vip', models.BooleanField(default=False, verbose_name='会员')),
                ('u_bank', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='账户余额')),
                ('u_create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
